Repository Ocramius/LazyMap, pull requests merged in 2021-09, with the labels that each got.

#93 Dependabot upgrade and PHP 8.1 support
  .github/dependabot.yml
  .github/workflows/benchmarks.yml
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/merge-dependabot-upgrades.yml
  .github/workflows/mutation-tests.yml
  .github/workflows/phpunit.yml
  .github/workflows/psalm.yml
Labels: enhancement

#112 Upgraded coding standard, mutation testing tooling and benchmark dependencies
  composer.json
  composer.lock
  phpbench.json
  phpcs.xml.dist
  src/LazyMap/AbstractLazyMap.php
Labels: enhancement, dependencies

#113 Fixed FQCN in README
  README.md
Labels: bug
